apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
      - name: carts
        image: weaveworksdemos/carts:0.4.8
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: CARTS_MONGO_URL
