apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: weaveworksdemos/front-end:0.3.12
        resources:
            requests:
              cpu : "20m"
              memory : "50Mi"
            limits:
              cpu: "30m"
              memory: "100Mi"
        ports:
        - containerPort: 8079
