apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: sock-shop
data:
  CARTS_MONGO_URL: mongodb://mongo-carts:27017/carts
  USERS_MONGO_URL: mongodb://user-db-svc:27017
  ORDERS_MONGO_URL: mongodb://mongo-orders:27017/orders

  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: socksdb
